### PR TITLE
remove the WRITE_EXTERNAL_STORAGE permission. fixes #3

### LINKED ISSUE #3: Remove Write External Storage permission
Why we need to "Write External Storage" permission , when we can store the data on internal Storage , it  adds for more permission to be given to the Apps which is not writing anything on external storage.

### PR DESCRIPTION
**Pull request by emmettbutler**

### CODE REVIEW

**Comment by kpuneet** [comment]
Hi Emmett,
Thanks for accommodating our concerns, We are working to verify this and can give you our feedback by EOD.
meanwhile I want to know what is the API Key 
"  ParselyTracker.sharedInstance("examplesite.com", this);" 

Is the "examplesite.com" shall be replaced by the website name for our product or is it something else ?

**Comment by emmett9001** [comment]
@kpuneet Correct. The apikey is the domain name you see in the top left of the Dash overview page (dash.parsely.com).

**Comment by kpuneet** [comment]
Thanks very much , I got it 
But do you know how to see the traffic from App on the dashboard once we integrate the SDK.

**Comment by emmett9001** [comment]
@kpuneet App traffic is currently denoted in the dashboard by the referrer - all native app traffic has the referrer [`parsely_mobile_sdk`](https://github.com/Parsely/parsely-android/blob/master/parsely/parselyandroid/ParselyTracker.java#L53)

**Comment by kpuneet** [comment]
@emmett9001 , I have tested the pull request the feature is complete , we are no longer asked to give WRITE_EXTERNAL_PERMISSION.
but the App is crashing  because of ANR  (DISK I/O) , it is reading and writing on the main thread .

We can't integrate Parsely in the current form, please let me know if you have any plan to modify it.

**Comment by emmett9001** [comment]
@kpuneet Please see the latest changes on this branch. I've added a parameter `enablePersistence` to `ParselyTracker.sharedInstance` that can be used to turn off all disk writes made by the SDK. Please note that setting this flag to `false` may cause some events not to be sent when devices have insufficient reception. You can try it out by starting your tracker instance with `ParselyTracker.sharedInstance("apikey.com", 60, "parsely_mobiole_sdk", false)`. Please give that a try and let me know here if it allows you to use the SDK. If it doesn't, I may need more information about the specific errors you're seeing.

**Comment by nseidm1** [comment]
Hi Emmett,

Disabling disk writes is not an acceptable solution, saving the queue to disk is an essential component of a modern tracking sdk. Please refactor the sdk to read/write from disk not on the UI thread. Please reach out to us when the refactoring work is complete so we can inform our managers that Parsely is approved for a HuffPost release.

**Comment by wzieba** [comment]
Closing as obsolete

**Pull request closed without merging**
